init:
  - git config --global core.autocrlf input

build: 'off'

matrix:
  fast_finish: true

environment:
  matrix:
    - nodejs_version: '10'
    - nodejs_version: '8'
    - nodejs_version: '6'

install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm i -g npm
  - npm i

test_script:
  - npm t
